// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Deploy MySQL and Service
Duration: 4:00

MySQL uses persistent storage.  Rather than writing the data directly into the container image itself, our example stores the MySQL in a Persistent Volume.  Before you can deploy the pod, you need to claim a persistent volume that can be mounted inside of the MySQL container:

[source, bash, subs="normal,attributes"]
----
$ *kubectl create -f mysql-pvc.yaml*
persistentvolumeclaim "mysql-pvc" created
----

CDK provides several *PersistentVolumes*, previously defined by the cluster administrator. These *PersistentVolumes* will be assigned based on the size claimed by the *PersistentVolumeClaim*.

You can examine the *PersistentVolumeClaim* with the following command:

[source, bash, subs="normal,attributes"]
----
$ *kubectl get pvc*
NAME        STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
mysql-pvc   Bound     pv0044    100Gi      RWO,ROX,RWX                  27s
----

You can then deploy both the MySQL Pod and the Service with a single command:

[source, bash, subs="normal,attributes"]
----
$ *kubectl create -f mysql-deployment.yaml -f mysql-service.yaml*
deployment "mysql" created
service "mysql" created
----

Lastly, you can see the pods and service status via the command line.  Recall the command you can use to see the status (hint: _kubectl get ..._).  Make sure the status is _Running_ before continuing.
