// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Deploy frontend
Duration: 5:00

A Kubernetes pod is a group of containers, tied together for the purposes of administration and networking. It can contain one or more containers.  All containers within a single pod will share the same networking interface, IP address, volumes, etc.  All containers within the same pod instance will live and die together.  It’s especially useful when you have, for example, a container that runs the application, and another container that periodically polls logs/metrics from the application container.

You can start a single Pod in Kubernetes by creating a Pod resource. However, a Pod created this way would be known as a link:https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replication-controllers-and-jobs[Naked Pod]. However, if a Naked Pod dies/exits, it will not be restarted by Kubernetes. A better way to start a pod, is by using a higher-level construct such as Replication Controller, Replica Set, or a Deployment.

A Replication Controller ensures that a specified number of pod "replicas" are running. If there are too many pods, it will kill some. If there are too few, the replication controller will start more. Unlike manually created pods, the pods maintained by a replication controller are automatically replaced if they fail, get deleted, or are terminated.

A Deployment provides declarative updates for Pods and Replication Controllers. You only need to describe the desired state in a Deployment object, and the Deployment controller will change the actual state to the desired state at a controlled rate for you. You can use deployments to easily:
- Create a Deployment to bring up a Replication Controller and Pods.
- Check the status of a Deployment to see if it succeeds or not.
- Later, update that Deployment to recreate the Pods (for example, to use a new image, or configuration).
- Rollback to an earlier Deployment revision if the current Deployment isn’t stable.
- Pause and resume a Deployment.

In this lab, because we are working with Kubernetes 1.2+, we will be using Deployment extensively. 

First create a Deployment using kubectl, the Kubernetes CLI tool:

[source, bash, subs="normal,attributes"]
----
$ *kubectl create -f frontend-deployment.yaml*
deployment "frontend-ui" created
----

You should see the frontend instances running:

[source, bash, subs="normal,attributes"]
----
$ *kubectl get pods -w*
NAME                  READY     STATUS              RESTARTS   AGE
frontend-ui-?????     0/1       ContainerCreating   0          2m
frontend-ui-?????     1/1       Running             0          2m
----

Hit CTRL+C to exit back to the shell prompt at any moment. 

NOTE: The _ContainerCreating_ status means that Kubernetes still downloading the image from the registry before creating the containers. 

#### Optional interlude: Look at your pod running in a docker container on the VM

Kubernetes is container format agnostic. In your lab, we are working with containers using the docker format. Keep in mind that Kubernetes architecture allows it to work with other container formats too. You can see that the docker container is running:

NOTE: If you are running minishift, run the following command first: `minishift ssh`. Don't forget to exit from minishift shell


[source, bash, subs="normal,attributes"]
----
[docker@minishift ~]$ *docker ps|grep microservices-frontend*
CONTAINER ID   IMAGE                                   COMMAND                 CREATED           STATUS            
52fb5e0aae73   rafabene/microservices-frontend:latest  "container-entrypoint"  14 minutes ago    Up 14 minutes     
....
----

