// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Get the Guestbook source
Duration: 3:00

Start by cloning the github repository for the Guestbook application and move into the kubernetes examples directory.

[source, bash, subs="normal,attributes"]
----
$ *git clone https://github.com/redhat-developer-demos/kubernetes-lab*
$ *cd kubernetes-lab/kubernetes* 
----

Kubernetes resources can be specified using link:http://yaml.org/[yaml] or link:http://www.json.org/[json] formats. 
We will be using the yaml files in this directory to decribe and deploy the Kubernetes objects in our development environment.  You are definitely encouraged to read them and see how pods, services, and others are declared.  We’ll walk through a couple of these files in detail.

