// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#### Internal Kubernetes networking
Duration: 7:00

In Kubernetes every pod has a unique IP address!  You can “login” into one of these pods by using the _kubectl exec_ command.  This can drop you into a shell and execute commands inside of the container.

First, find the name of the both helloworld-service-vertx pods:

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ *kubectl get pods -l app=helloworld-service-vertx*
NAME                             READY     STATUS    RESTARTS   AGE
helloworld-service-vertx-?????   1/1       Running   0          14m
helloworld-service-vertx-?????   1/1       Running   0          15m
----

NOTE: Note that we used the parameter _-l app=helloworld-service-vertx_. This parameter allows us to specify labels as filter. The label _app=helloworld-service-vertx_ was defined in the ReplicationController as a template for all pods.

Then, use _kubectl exec_ to exucute a _"bash"_ process into the container:

[source, bash, subs="normal,attributes"]
----
$ *kubectl exec -it helloworld-service-vertx-????? bash*
[jboss@helloworld-service-vertx-????? ~]$ _
----

You are now in a shell inside of the helloworld-service-vertx container.  You can run _ps_, and _hostname_:

[source, bash, subs="normal,attributes"]
----
[jboss@helloworld-service-vertx-???? ~]$ *ps aux*
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
jboss        1  0.9  0.6 2693920 53412 ?       Ssl  20:48   0:01 java -Dvertx.di
jboss       21  0.0  0.0  13816  1784 ?        Ss   20:49   0:00 bash
jboss       36  0.0  0.0  49468  1664 ?        R+   20:51   0:00 ps aux

[jboss@helloworld-service-vertx-???? ~]$ *hostname -i*
172.17.0.7

[jboss@helloworld-service-vertx-???? ~]$ *exit*
exit
----

Don’t forget to exit :).  

[TIP]
====
You can begin to have a taste of some of the OpenShift enhancements now.
OpenShift Client (oc) allows you to easily access the shell through the command `oc rsh helloworld-service-vertx-?????`
====

Try it with another the other pod and see its IP address.

Since we are running two instances of the Hello World Service (one instance in one pod), and that the IP addresses are not only unique, but also ephemeral - how will a client reach our services? We need a way to discover the service.

In Kubernetes, Service Discovery is a first class citizen. We created a Service that will:

- act as a load balancer to load balance the requests to the pods, and
- provide a stable IP address, allow discovery from the API, and also create a DNS name!

If you login into a container (find and use the frontend-ui container), you can access the helloworldservice via the DNS name:

[source, bash, subs="normal,attributes"]
----
$ *kubectl exec -it frontend-ui-????? bash*

bash-4.2$* wget -qO- http://helloworld-service-vertx:8080/api/hello/Rafael*
Hello Rafael from helloworld-service-vertx-a4zq3 with 1.0

bash-4.2$ *exit*
exit
----

Pretty simple right!? 
