// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#### Using ConfigMap

In this section, we'll use Kubernetes 1.2's new feature, ConfigMap, to configure the application. You can store multiple string-based configuration files inside of a single ConfigMap configuration. In our example, we'll store Vert.x's config.json into a ConfigMap entry.

First, update the _kubernetes-lab/hellworld-service/config.json_ with a new configuration value:
[source, bash, subs="normal,attributes"]
----
$ *cd kubernetes-lab/hellworld-service/*
$ *vi config.json*
----
include::includes/tip.adoc[]

Here is a suggestion for you:

[source, json, subs="normal,attributes"]
----
{
  "GREETING": "Hello {name} from ConfigMap"
}
----

Next, create a ConfigMap entry with this file:

[source, bash, subs="normal,attributes"]
----
$ *oc create configmap greeting-config --from-file=config.json*
configmap "greeting-config" created
----

Let's take a look inside the newly created entry:

[source, bash, subs="normal,attributes"]
----
$ *oc edit configmap greeting-config*
# HINT: Type ':wq' to exit from vi
----

You'll see that the _config.json_ is now part of the YAML file:

[source, yaml, subs="normal,attributes"]
----
apiVersion: v1
data:
  *config.json: |
    {
      "GREETING": "Hello {name} from ConfigMap"
    }*
kind: ConfigMap
...
----

You can, of course, edit this ConfigMap in the editor too. If you do, edit only the value for the greeting variable.

There are several ways to access the values in this ConfigMap:

* Mount the entries (in our case, config.json) as a file.
* Access from the Kubernetes API (we won't cover this today).

Let's see how we can mount the configurations as files under a specific directory, e.g., _/etc/config/config.json_.

First, edit the Helloworld Service Deployment:

[source, bash, subs="normal,attributes"]
----
$ *oc edit deployment helloworld-service-vertx*
----
include::includes/tip.adoc[]

In the editor, add volumes and volume mounts (important - indentation matters!):

[source,yaml, subs="normal,attributes"]
----
apiVersion: v1
kind: DeploymentConfig
...
spec:
...
  template:
    ...
    spec:
      *volumes:
      - name: config-volume
        configMap:
          name: greeting-config*
      containers:
      - image: rafabene/microservices-helloworld-vertx:1.0
        *volumeMounts:
        - name: config-volume
          mountPath: /etc/config*
      ...
----

This will make the configuration file available as the file _/etc/config/config.json_. Let's verify by going into the pod itself (remember how to do this by using _kubectl exec_? You can also use _oc exec_, but now you will learn another option: _oc rsh_):

First, find the pod name:

[source, bash, subs="normal,attributes"]
----
$ *oc get pods*
NAME                               READY     STATUS    RESTARTS   AGE
...
helloworld-service-vertx-7-e1o5u   1/1       Running   0          54s
helloworld-service-vertx-7-sgosp   1/1       Running   0          40s
...
----

Then, run a shell inside the pod, and see what's in _/etc/config_:

[source,bash, subs="normal,attributes"]
----
$ *oc rsh helloworld-service-vertx-7-?????*

sh-4.2$ *ls /etc/config/*
config.json

sh-4.2$ *cat /etc/config/config.json*
{
  "GREETING": "Hello {name} from ConfigMap"
}

sh-4.2$ *exit*
exit
----

NOTE: Don't forget to exit out of the pod environment!

Great, the file is there, but the application needs to be configured to reference to the file. Vert.x can reference to an external configuration with the command line argument:

[source,subs="normal,attributes"]
----
-conf /etc/config/config.json
----

Recall how you were able to configure the command line arguments in the previous steps. You know the drill. Edit the Helloworld Service Deployment and add the arguments:

[source,yaml, subs="normal,attributes"]
----
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
...
  template:
    ...
    spec:
      ... 
      containers:
      - image: rafabene/microservices-helloworld-vertx:...
        *args:
        - -conf 
        - /etc/config/config.json*
      ...
----

Check the application to see it is using the new greeting string.

Last, but not least, you can also specify simple key/value pairs in ConfigMap, and then expose them directly as environmental variables too. See the http://kubernetes.io/docs/user-guide/configmap/[ConfigMap guide] for more examples.
