// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#### Environmental Variable

http://vertx.io/[Vert.X] can read the override configuration directly from an environment variable. In this case, the environment variable is defaulted to _greeting_. You can specify the environmental variable directly using the _oc_ command:

[source, bash, subs="normal,attributes"]
----
$ *oc env deployment helloworld-service-vertx GREETING='Hello {name} from envvar!'*
deployment "helloworld-service-vertx" updated
----

Again, through the use of *Kubernetes Deployment*, it'll rolling update all the replicas with the new configuration! If you were to refresh the application, you'll notice that there are no intermittent errors because we also have health checks and readiness checks in place.

Check the application to see it is using the new Greeting string.

Let's remove the defined variable:

[source, bash, subs="normal,attributes"]
----
$ *oc env deployment helloworld-service-vertx GREETING-*
deployment "helloworld-service-vertx" updated
----

NOTE: The '-' means that we want to remove that environment var from the Deployment.