// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Managing Credentials
Duration: 20:00

ConfigMap is great to store text-based configurations. Depending on your use cases, it may not be the best place to store your credentials (which sometimes may be a binary file rather than text). Secrets can be used to hold sensitive information, such as passwords, OAuth tokens, and SSH keys. Entries in Secrets are Base64 encoded. However, Secrets are not additionally encrypted when stored in Kubernetes.

In this section, we'll create a Secret that contains the MySQL username and password. We'll subsequently update both the MySQL Replication Controller and the Guestbook Service to refer to the same credentials.

First, let's create a Secret with username and password the command line:

[source, bash, subs="normal,attributes"]
----
$ *oc create secret generic mysql-secret \
       --from-literal=username=app,password=1337*
secret "mysql-secret" created
----

If you look into the newly created Secret, you'll see that the values are Base64 encoded:

[source, bash, subs="normal,attributes"]
----
$ *oc edit secret mysql-secret*
# HINT: Type ':wq' to exit from vi
----

In the Editor, you'll see:

[source, yaml, subs="normal,attributes"]
----
apiVersion: v1
data:
  password: MTMzNw==
  username: YXBw
kind: Secret
...
----

In the pods, you can access these values a couple of ways:

* Mount each entry as a file under a directory (similar to what we did with ConfigMap)
* Use http://kubernetes.io/docs/user-guide/downward-api/#exposing-pod-information-into-a-container[Downward API] to expose each entry as an Environmental Variable (which you can also do with ConfigMap).

Since the MySQL container already expects username and password to be configured using the Environmental Variables, we'll use the latter (Downward API) approach.

First, in kubernetes/ directory, edit the mysql-deployment.yaml. Edit the mysql Deployment and modify the variables MYSQL_USER and MYSQL_PASSWORD with the following values:

[source, yaml, subs="normal,attributes"]
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
...
  template:
    spec:
      containers:
      - resources:
        ...
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
        - name: MYSQL_DATABASE
          value: guestbook
        *- name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

We'll also need to recreate the *PersistentVolumeClaim* too in order to force MySQL to create the user):

[source, bash, subs="normal,attributes"]
----
$ *oc delete pvc/mysql-pvc deployment/mysql*
persistentvolumeclaim "mysql-pvc" deleted
replicationcontroller "mysql" deleted

[vagrant@rhel-cdk kubernetes]$ *oc create -f mysql-pvc.yaml -f mysql-deployment.yaml*
persistentvolumeclaim "mysql-pvc" created
deployment "mysql" created
----

Once MySQL comes back up, test the connection by running MySQL client directly inside the pod. Recall how you can use _oc rsh_ to do this:

[source, bash, subs="normal,attributes"]
----
$ *oc get pods*
NAME                              READY     STATUS    RESTARTS   AGE
...
mysql-...                         1/1       Running   0          2m
...

$ *oc rsh mysql-...*
sh-4.2$ *mysql -u app -p -h 127.0.0.1*
Enter password: *1337*
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.6.24 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> *exit*
Bye
sh-4.2$ *exit*
exit
----

Great! Now MySQL is picking up the credentials from the Secret.

Next, configure the Guestbook Service and update the Environmental Variables too.

Now edit the Guestbook Service deployment and  add a couple of environment variables:

[source, yaml, subs="normal,attributes"]
----
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  ...
  template:
  ...
    spec:
      …
      containers:
      - image: rafabene/microservices-guestbook:1.0
        *env:
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

Once the deployment completes, check that the application is still working.