// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Rolling Update
Duration: 10:00

It’s easy to update & rollback. 

In this lab, we'll switch to the _frontend/_ directory and make a minor change to the index.html (e.g., change the background color, title, etc.). After that, rebuild the container.


[source, bash, subs="normal,attributes"]
----
$ *cd kubernetes-lab/frontend*
$ *vi index.html*
----
[TIP]
====
HINT 1: Change the _<h2>Say Hi</h2>_ line, but feel free to change any HTML content that that you want

HINT 2: Type *':51'* to go to that line

HINT 3: Type *'i'* to enter in edit mode 

HINT 4: Type *':wq'* to exit from vi
====

Kubernetes needs to be aware of the new docker image with the changes that you introduced.

include::docker-image-minishift.adoc[]

[source, bash, subs="normal,attributes"]
----
$ *docker build -t rafabene/microservices-frontend:2.0 .*
----

Now we will use the _kubectl rolling-update_ command to perform the rolling update. We create a new *ReplicationController* called frontend-ui-2 that contains the new image.

[source,bash, subs="normal,attributes"]
----
$ *kubectl set image  deployment/frontend-ui frontend-ui=rafabene/microservices-frontend:2.0*
deployment "frontend-ui" image updated
----

That's it! Kubernetes will performed a rolling update to update all the versions from 1.0 to 2.0.

NOTE: This 2.0 version only exists in your local registry. It will only be available if you have built it using the _docker build_ command.
