// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Scaling
Duration: 5:00

We have seem that *Deployments* keep the same ammount of replicas running. Let's check the number of pods again. Execute:

[source, bash, subs="normal,attributes"]
----
$ *kubectl get pods*
NAME                             READY     STATUS    RESTARTS   AGE
frontend-ui-6jy22                1/1       Running   0          24m
frontend-ui-7tcgx                1/1       Running   0          24m
guestbook-service-gxjnx          1/1       Running   0          19m
helloworld-service-vertx-edux9   1/1       Running   0          20m
helloworld-service-vertx-lq1m0   1/1       Running   0          21m
mysql-q9k7p                      1/1       Running   0          21m
----

Scaling the number of replicas of our Hello World service is as simple as running :

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ *kubectl scale deployment helloworld-service-vertx --replicas=6*
deployment "helloworld-service-vertx" scaled
----

You can very quickly see that the replication controller has been updated:

[source, bash, subs="normal,attributes"]
----
$ *kubectl get deployments*
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
frontend-ui                2         2         2            2           3h
guestbook-service          1         1         1            1           2h
helloworld-service-vertx   6         6         6            6           2h
mysql                      1         1         1            1           2h

$ *kubectl get pods*
NAME                                        READY     STATUS    RESTARTS   AGE
frontend-ui-2676544744-3k1p6                1/1       Running   0          3h
frontend-ui-2676544744-b88hg                1/1       Running   0          3h
guestbook-service-114023015-8x9j8           1/1       Running   0          2h
helloworld-service-vertx-3644252884-73cxk   1/1       Running   0          48s
helloworld-service-vertx-3644252884-t364t   1/1       Running   0          2h
helloworld-service-vertx-3644252884-v5t67   1/1       Running   0          48s
helloworld-service-vertx-3644252884-wct43   1/1       Running   0          48s
helloworld-service-vertx-3644252884-x7ggl   1/1       Running   0          48s
helloworld-service-vertx-3644252884-xxvzh   1/1       Running   0          2h
mysql-471477625-rnjt1                       1/1       Running   0          2h
----

Reduce the number of replicas back to 2 so that we can free up resources for the later labs:

[source, bash, subs="normal,attributes"]
----
$ *kubectl scale deployment helloworld-service-vertx --replicas=2*
deployment "helloworld-service-vertx" scaled
----
