// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Setup environments
Duration: 15:00

This section describes what, how, and where to install the software needed for this lab. This lab is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab.

### Hardware

- Operating System: Windows 7 (SP1), Mac OS X (10.8 or later), Fedora (21 or later)
- Memory: At least 4 GB+, preferred 8 GB

### Software

#### Vagrant

Vagrant is a tool for building complete development environments. With an easy-to-use workflow and focus on automation, Vagrant lowers development environment setup time, increases development/production parity, and makes the "works on my machine" excuse a relic of the past.

Downloads are available from: link:https://www.vagrantup.com/downloads.html[]

#### A virtualization platform (hypervisor) - VirtualBox

Vagrant needs a hypervisor to create a development environment. 

Downloads are available from link:https://www.virtualbox.org/wiki/Downloads[] .

[WARNING]
====
Linux Users:

. Have your kernel updated
. Users should have the GNU compiler, build and header files for your current Linux kernel
. Create a `/usr/src/linux` link to the current kernel source
====

#### CDK

link:http://developers.redhat.com/products/cdk/overview/[Red Hat Container Development Kit] is a pre-built container development environment based on RHEL - Red Hat Enterprise Linux to help you get started developing container-based applications quickly. 

Developers can get the Red Hat Container Development Kit via no-cost Red Hat Enterprise Linux® Developer Suite subscription for development purposes by link:https://developers.redhat.com/download-manager/link/1350474[registering and downloading] through link:developers.redhat.com/[developers.redhat.com]. 

IMPORTANT: Make sure to take notes of your username(email) and password. It will be used as the free subscription of RHEL.

Downloads are available from link:http://developers.redhat.com/products/cdk/download/[]

[WARNING]
====
. You will need:
.. link:http://developers.redhat.com/download-manager/file/cdk-2.1.0.zip[cdk-2.1.0.zip]
.. link:https://developers.redhat.com/download-manager/file/rhel-cdk-kubernetes-7.2-25.x86_64.vagrant-virtualbox.box[RHEL 7.2 for VirtualBox]

====

Setup CDK:
- Install Vagrant and VirtualBox
- Install Vagrant plugins
- Add Vagrant box with *vagrant box* command
- Extract CDK
- Start the environment with *vagrant up*

[source,bash,subs="normal,attributes"]
----
$ *vagrant box add cdkv2* **<BOX_PATH>/rhel-cdk-kubernetes-7.2-25.x86_64.vagrant-virtualbox.box**
$ *unzip cdk-2.1.0.zip*
$ *cd cdk/components/rhel/rhel-ose*
$ *vagrant plugin install vagrant-service-manager vagrant-registration*
$ *vagrant up*
$ *vagrant ssh*
[vagrant@rhel-cdk kubernetes]$ .
----

IMPORTANT: If you use an invalid username/password, you will need to destroy your VM using **vagrant destroy** and start it again.