// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## Setup environment
Duration: 15:00

This section describes what, how, and where to install the software needed for this lab. This lab is designed for a BYOL (Bring Your Own Laptop) style hands-on-lab.

### Hardware

- Operating System: Windows 7 (SP1), Mac OS X (10.8 or later), Fedora (21 or later)
- Memory: At least 4 GB+, preferred 8 GB

### Software

#### Development tools

Make sure to have the following tools/packages installed:

- GIT
- Maven
- Kubernetes binaries ( <https://kubernetes.io/docs/tasks/tools/install-kubectl/> )

#### kubectl

To install kubectl binary, follow the link:https://kubernetes.io/docs/tasks/tools/install-kubectl/[Install and Set Up kubectl] tutorial

TIP: macOS users can install `kubectl` through homebrew using the following command `brew install kubectl`

#### oc 

To install oc, Download it from https://github.com/openshift/origin/releases

TIP: macOS users can isntall `oc` through homebrew using the following command: `brew install openshift-cli`

### Login in the cluster

This lab uses link:https://www.openshift.org/[OpenShift], which is an Enterprise distribution of Kubernetes. Because of some Enterprise features like security, it's needed to authenticate against this cluster.

To authenticate in the cluster, you need to access to the `oc` binary. You can add the oc binary to you path by running the following command:

[source,bash,subs="normal,attributes"]
----
# Login in the cluster
$ oc login {ocp-cluster}
----

The credentials are: userX / openshift. X is your assigned number

Next, you will need to create a project for you:

[source,bash,subs="normal,attributes"]
----
# Create a new project. X is your number
$ oc new-project labX
----
