// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Create your Kubernetes Cluster
Duration: 5:00

The first step is to create a cluster to work with. We will create a Kubernetes cluster using Google Container Engine.

In Cloud Shell, don’t forget to set the default zone and region configuration if you haven’t already:
include::custom/config-region.adoc[]

Create a Kubernetes cluster in Google Cloud Platform is very easy! Use Container Engine to create a cluster:

[subs="normal,attributes"]
----
$ *gcloud container clusters create guestbook \
      --num-nodes 4 \
      --scopes cloud-platform*
----

This will take a few minutes to run. Behind the scenes, it will create Google Compute Engine instances, and configure each instance as a Kubernetes node. These instances don’t include the Kubernetes Master node. In Google Container Engine, the Kubernetes Master node is managed service so that you don’t have to worry about it!

The scopes parameter is important for this lab. Scopes determine what Google Cloud Platform resources these newly created instances can access.  By default, instances are able to read from Google Cloud Storage, write metrics to Google Cloud Monitoring, etc. For our lab, we add the _cloud-platform_ scope to give us more privileges, such as writing to Cloud Storage as well.

[TIP]
====
While this goes on you might enjoy watching this short video https://youtu.be/7vZ9dRKRMyc!
====

You can see the newly created instances in the Google Compute Engine > VM Instances page.
