// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#### Optional interlude: Look at your pod running in a Docker container on the VM

Kubernetes is container format agnostic. In your lab, we are working with Docker containers. Keep in mind that Kubernetes work with other container formats too. You can see that the Docker container is running on one of the machines.  First, find the node name that Kubernetes scheduled this container to:

[subs="normal,attributes"]
----
$ *kubectl get pods -owide*
NAME              READY     STATUS    RESTARTS   AGE       NODE
frontend-ui-...   1/1       Running   0          11m       gke-guestbook-...
frontend-ui-...   1/1       Running   0          11m       gke-guestbook-...
----

The value under the label NODE is the name of the node.

You can then SSH into that node: 

[subs="normal,attributes"]
----
$ *gcloud compute ssh <node-name>*
Warning: Permanently added '104.197.182.219' (ECDSA) to the list of known hosts.
Linux gke-guestbook-default-pool-a27323b1-pzt9 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64

Welcome to Kubernetes v1.2.4!

You can find documentation for Kubernetes at:
  http://docs.kubernetes.io/

You can download the build image for this release at:
  https://storage.googleapis.com/kubernetes-release/release/v1.2.4/kubernetes-src.tar.gz

It is based on the Kubernetes source at:
  https://github.com/kubernetes/kubernetes/tree/v1.2.4

For Kubernetes copyright and licensing information, see:
  /usr/local/share/doc/kubernetes/LICENSES

someuser@<node-name>:~$
----

You can then use docker command line to see the running container:

[subs="normal,attributes"]
----
someuser@<node-name>:~$ *sudo docker ps*
CONTAINER ID   IMAGE                                   COMMAND                 CREATED           STATUS            
52fb5e0aae73   rafabene/microservices-frontend:latest  "container-entrypoint"  14 minutes ago    Up 14 minutes     
....
someuser@<node-name>:~$ *exit*
logout
----

*End of Optional interlude: make sure you exit from the SSH* before you continue.

If you see other containers running don’t worry, those are other services that are part of the management of Kubernetes clusters.