// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Deploy MySQL and Service
Duration: 4:00

MySQL uses persistent storage.  Rather than writing the data directly into the container image itself, our example stores the MySQL in a Google Compute Engine disk.  Before you can deploy the pod, you need to create a disk that can be mounted inside of the MySQL container:

[subs="normal,attributes"]
----
$ *gcloud compute disks create mysql-disk --size 200GB*
Created [...].
NAME        ZONE           SIZE_GB  TYPE         STATUS
mysql-disk  ...            200      pd-standard  READY
----

You can then deploy both the MySQL Pod and the Service with a single command:

[subs="normal,attributes"]
----
$ *kubectl create -f mysql-deployment.yaml -f mysql-service.yaml --record*
deployment "mysql" created
service "mysql" created
----

Lastly, you can see the pods and service status via the command line.  Recall the command you can use to see the status (hint: _kubectl get …_).  Make sure the status is _Running_ before continuing.
