// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Managing Credentials
Duration: 20:00

ConfigMap is great to store text-based configurations. Depending on your use cases, it may not be the best place to store your credentials (which sometimes may be a binary file rather than text). Secrets can be used to hold sensitive information, such as passwords, OAuth tokens, and SSH keys. Entries in Secrets are Base64 encoded. However, Secrets are not additionally encrypted when stored in Kubernetes.

In this section, we'll create a Secret that contains the MySQL username and password. We'll subsequently update both the MySQL Replication Controller and the Guestbook Service to refer to the same credentials.

First, let's create a Secret with username and password the command line:

[source,subs="normal,attributes"]
----
$ *kubectl create secret generic mysql-secret \
      --from-literal=username=app,password=1337*
secret "mysql-secret" created
----

If you look into the newly created Secret, you'll see that the values are Base64 encoded:

[source,subs="normal,attributes"]
----
$ *kubectl edit secret mysql-secret*
----

In the Editor, you'll see:

[source,subs="normal,attributes"]
----
apiVersion: v1
data:
  password: MTMzNw==
  username: YXBw
kind: Secret
...
----

In the pods, you can access these values a couple of ways:

* Mount each entry as a file under a directory (similar to what we did with ConfigMap)
* Use link:http://kubernetes.io/docs/user-guide/downward-api/#exposing-pod-information-into-a-container[Downward API] to expose each entry as an Environmental Variable (which you can also do with ConfigMap).

Since the MySQL container already expects username and password to be configured using the Environmental Variables, we'll use the latter (Downward API) approach.

First, in _kubernetes/_ directory, edit the mysql-deployment.yaml:

[source,subs="normal,attributes"]
----
apiVersion: v1
kind: Deployment
metadata:
  name: mysql
spec:
...
  template:
    spec:
      containers:
      - resources:
        ...
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
        - name: MYSQL_DATABASE
          value: app
        *- name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

Then, apply the change by deleting the MySQL Replication Controller and recreating it (due to how MySQL container initializes, we'll also need to recreate the Google Compute Engine disk too in order to force MySQL to create the user):

[source,subs="normal,attributes"]
----
$ *kubectl delete deployment mysql*
$ *gcloud compute disks delete mysql-disk*
The following disks will be deleted. Deleting a disk is irreversible
and any data on the disk will be lost.
 - [mysql-disk] in [us-central1-b]

Do you want to continue (Y/n)?  y

Deleted [...]
$ *gcloud compute disks create mysql-disk --size 200GB*
$ *kubectl create -f mysql-deployment.yaml --record*
----

Once MySQL comes back up, test the connection by running MySQL client directly inside the pod. Recall how you can use _kubectl exec_ to do this:

[source,subs="normal,attributes"]
----
$ *kubectl get pods*
NAME                              READY     STATUS    RESTARTS   AGE
...
mysql-...                         1/1       Running   0          2m
...

$ *kubectl exec -it mysql-... /bin/bash*
root@mysql-...:/# mysql -u app -p
Enter password: 1337
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.6.30 MySQL Community Server (GPL)
Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> *exit*
Bye
root@mysql-...:/# *exit*
----

Great! Now MySQL is picking up the credentials from the Secret.

Next, configure the Guestbook Service, by editing the Deployment and updating the Environmental Variables too:

[source,subs="normal,attributes"]
----
$ *kubectl edit deployment guestbook-service*
----

Then, add a couple of Environmental Variables:

[source,subs="normal,attributes"]
----
kind: Deployment
...
spec:
  ...
  template:
  ...
    spec:
      …
      containers:
      - image: rafabene/microservices-guestbook:latest
        *env:
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

And that's it!

Once the deployment completes, check that the application is still working.