// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Autoscaling
Duration: 5:00

Kubernetes 1.2 has built-in Horizontal Pod Autoscaling based on CPU utilization (and custom metrics!). We will only cover autoscaling based on CPU utilization in this lab, since the custom metrics scaling is still in Alpha.

To set up horizontal autoscaling is extremely simple:

[source,subs="normal,attributes"]
----
$ *kubectl autoscale deployment helloworld-service-vertx --min=2 --max=10 --cpu-percent=80*
----

Behind the scenes, Kubernetes will periodically (by default, every 30 seconds) collect CPU utilization and determine the number of pods needed.

You can see the current status of the autoscaler by using the describe command:

[source,subs="normal,attributes"]
----
$ *kubectl describe hpa helloworld-service-vertx*
Name:                       helloworld-service-vertx
Namespace:                  default
Labels:                     <none>
Annotations:                <none>
CreationTimestamp:          Thu, 02 Jun 2016 13:30:23 -0400
Reference:                  Deployment/helloworld-service-vertx/scale
Target CPU utilization:     80%
Current CPU utilization:    1%
Min replicas:               2
Max replicas:               10
Events:
....
----

It's going to be a little difficult to generate the load needed to kick off the autoscaler. We won't do that during the lab.

Learn more about Horizontal Pod Autoscaling in the link:http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/[guide]
