// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Managing Credentials
Duration: 20:00

ConfigMap is great to store text-based configurations. Depending on your use cases, it may not be the best place to store your credentials (which sometimes may be a binary file rather than text). Secrets can be used to hold sensitive information, such as passwords, OAuth tokens, and SSH keys. Entries in Secrets are Base64 encoded. However, Secrets are not additionally encrypted when stored in Kubernetes.

In this section, we'll create a Secret that contains the MySQL username and password. We'll subsequently update both the MySQL Replication Controller and the Guestbook Service to refer to the same credentials.

First, let's create a Secret with username and password the command line:

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk hellworld-service]$ *oc create secret generic mysql-secret \
       --from-literal=username=app,password=1337*
secret "mysql-secret" created
----

If you look into the newly created Secret, you'll see that the values are Base64 encoded:

[source, bash, subs="normal,attributes"]
----
vagrant@rhel-cdk hellworld-service]$ *oc edit secret mysql-secret*
# HINT: Type ':wq' to exit from vi
----

In the Editor, you'll see:

[source, yaml, subs="normal,attributes"]
----
apiVersion: v1
data:
  password: MTMzNw==
  username: YXBw
kind: Secret
...
----

In the pods, you can access these values a couple of ways:

* Mount each entry as a file under a directory (similar to what we did with ConfigMap)
* Use http://kubernetes.io/docs/user-guide/downward-api/#exposing-pod-information-into-a-container[Downward API] to expose each entry as an Environmental Variable (which you can also do with ConfigMap).

Since the MySQL container already expects username and password to be configured using the Environmental Variables, we'll use the latter (Downward API) approach.

First, in _kubernetes/_ directory, edit the mysql-rc.yaml:

[source, yaml, subs="normal,attributes"]
----
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
...
  template:
    spec:
      containers:
      - resources:
        ...
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword
        - name: MYSQL_DATABASE
          value: guestbook
        *- name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

Then, apply the change by deleting the MySQL *ReplicationController* and recreating it (due to how MySQL container initializes, we'll also need to recreate the *PersistentVolumeClaim* too in order to force MySQL to create the user):

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ *oc delete pvc/mysql-pvc rc/mysql*
persistentvolumeclaim "mysql-pvc" deleted
replicationcontroller "mysql" deleted

[vagrant@rhel-cdk kubernetes]$ *oc create -f mysql-pvc.yaml -f mysql-rc.yaml*
persistentvolumeclaim "mysql-pvc" created
replicationcontroller "mysql" created
----

Once MySQL comes back up, test the connection by running MySQL client directly inside the pod. Recall how you can use _oc rsh_ to do this:

[source, bash, subs="normal,attributes"]
----
$ *oc get pods*
NAME                              READY     STATUS    RESTARTS   AGE
...
mysql-...                         1/1       Running   0          2m
...

$ *oc rsh mysql-...*
sh-4.2$ *mysql -u app -p -h 127.0.0.1*
Enter password: *1337*
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.6.24 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> *exit*
Bye
sh-4.2$ *exit*
exit
----

Great! Now MySQL is picking up the credentials from the Secret.

Next, configure the Guestbook Service and update the Environmental Variables too.

NOTE: Since this service doesn't have a *DeploymentConfig*, we will update the service by editing the _guestbookservice-rc.yaml_ file.

Add a couple of environment variables:

[source, yaml, subs="normal,attributes"]
----
apiVersion: v1
kind: ReplicationController
...
spec:
  ...
  template:
  ...
    spec:
      …
      containers:
      - image: rafabene/microservices-guestbook:1.0
        *env:
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password*
...
----

Don't forget to replace the *ReplicationController* manually.

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ oc delete rc/guestbook-service
replicationcontroller "guestbook-service" deleted
[vagrant@rhel-cdk kubernetes]$ oc create -f guestbookservice-rc.yaml
replicationcontroller "guestbook-service" created
----

NOTE: The modified file doesn't contain the *ReadinessProbe*, so you will need to check manually if Guestbook Service is ready to receive requets. HINT: Use oc logs -f rc/guestbook-service

Once the deployment completes, check that the application is still working.