// JBoss, Home of Professional Open Source
// Copyright 2016, Red Hat, Inc. and/or its affiliates, and individual
// contributors by the @authors tag. See the copyright.txt in the
// distribution for a full listing of individual contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

### Scaling
Duration: 5:00

Scaling the number of replicas of our Hello World service is as simple as running :

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ *kubectl scale rc helloworld-service-vertx --replicas=6*
replicationcontroller "helloworld-service-vertx" scaled
----

You can very quickly see that the replication controller has been updated:

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ kubectl get rc
CONTROLLER                 CONTAINER(S)               IMAGE(S)                                      SELECTOR                                          REPLICAS   AGE
frontend-ui                frontend-ui                rafabene/microservices-frontend:1.0           app=frontend-ui                                   2          8m
guestbook-service          guestbook-service          rafabene/microservices-guestbook:1.0          app=guestbook-service,lab=kubernetes-lab          1          2m
helloworld-service-vertx   helloworld-service-vertx   rafabene/microservices-helloworld-vertx:1.0   app=helloworld-service-vertx,lab=kubernetes-lab   6          3m
mysql                      mysql                      openshift/mysql-56-centos7                    app=mysql,lab=kubernetes-lab                      1          4m

[vagrant@rhel-cdk kubernetes]$ *kubectl get pods*
NAME                             READY     STATUS    RESTARTS   AGE
frontend-ui-cfro2                1/1       Running   0          17m
frontend-ui-jwneu                1/1       Running   0          17m
guestbook-service-kfwht          1/1       Running   0          10m
helloworld-service-vertx-8lsrk   1/1       Running   0          33s
helloworld-service-vertx-8ok55   1/1       Running   0          10m
helloworld-service-vertx-aekwy   1/1       Running   0          33s
helloworld-service-vertx-igkad   1/1       Running   0          33s
helloworld-service-vertx-qtfd7   1/1       Running   0          12m
helloworld-service-vertx-toohm   1/1       Running   0          33s
mysql-jn34r                      1/1       Running   0          13m
----

Reduce the number of replicas back to 2 so that we can free up resources for the later labs:

[source, bash, subs="normal,attributes"]
----
[vagrant@rhel-cdk kubernetes]$ *kubectl scale rc helloworld-service-vertx --replicas=2*
----
